# Question 3

In [60]:
import pandas as pd
import numpy as np
from sklearn.metrics import log_loss
from sklearn.tree import DecisionTreeClassifier

In [61]:
#reading the data 
data_frame = pd.read_csv("Data_for_UCI_named.csv")
data_frame.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [62]:
# 3-(a)
column_index = [4,12]
final_dataframe = data_frame.drop(data_frame.columns[column_index],axis=1)
final_dataframe.head()

,tau1,tau2,tau3,tau4,p2,p3,p4,g1,g2,g3,g4,stabf
0,2.959060,3.079885,8.381025,9.780754,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,unstable
1,9.304097,4.902524,3.047541,1.369357,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,stable
2,8.971707,8.848428,3.046479,1.214518,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,unstable
3,0.716415,7.669600,4.486641,2.340563,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,unstable
4,3.134112,7.608772,4.943759,9.857573,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,unstable

In [63]:
# 3-(b)
final_dataframe['stabf']=final_dataframe['stabf'].replace('stable',1)
final_dataframe['stabf']=final_dataframe['stabf'].replace('unstable',0)
final_dataframe.head()

,tau1,tau2,tau3,tau4,p2,p3,p4,g1,g2,g3,g4,stabf
0,2.959060,3.079885,8.381025,9.780754,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0
1,9.304097,4.902524,3.047541,1.369357,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,1
2,8.971707,8.848428,3.046479,1.214518,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0
3,0.716415,7.669600,4.486641,2.340563,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0
4,3.134112,7.608772,4.943759,9.857573,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0

In [64]:
# 3-(c)
test_percent = 20
total_rows = final_dataframe.shape[0] 
test_subset=(test_percent*total_rows//100)
test = final_dataframe.iloc[0:test_subset]

In [65]:
# 3-(d)
train1 = final_dataframe.iloc[test_subset:]
train_percent = 75
total_rows2 = train1.shape[0]
train_subset=(train_percent*total_rows2//100)
train = train1.iloc[0:train_subset]
valid = train1.iloc[train_subset:]

# Question 4

In [66]:
# 4-(a)
train_predictor = train.iloc[:,0:11]
train_target = train.iloc[:,11]
gini_tree = DecisionTreeClassifier(criterion='gini', max_depth = 5)
gini_model=gini_tree.fit(train_predictor,train_target)

In [67]:
# 4-(b)
valid_predictor = valid.iloc[:,0:11]
valid_target = valid.iloc[:,11]
predictions=gini_model.predict_proba(valid_predictor)
entropy1 = log_loss(valid_target,predictions)
print(entropy1)

0.502776075040931

In [68]:
# 4-(c)
info_gain_tree = DecisionTreeClassifier(criterion='entropy', max_depth = 5)
info_gain_model=info_gain_tree.fit(train_predictor,train_target)

In [69]:
# 4-(d)
predictions2=info_gain_model.predict_proba(valid_predictor)
entropy2 = log_loss(valid_target,predictions2)
print(entropy2)

0.5625145619753155

In [70]:
# 4-(e)
# Model with Gini performed better due to lower value of entropy

train_predictor = train1.iloc[:,0:11]
train_target = train1.iloc[:,11]
gini_tree = DecisionTreeClassifier(criterion='gini', max_depth = 5)
gini_model=gini_tree.fit(train_predictor,train_target)


test_predictor = test.iloc[:,0:11]
test_target = test.iloc[:,11]
predictions=gini_model.predict_proba(test_predictor)
entropy3 = log_loss(test_target,predictions)
print(entropy3)

0.46064005864631713

In [71]:
# gini performed better